### ISSUE TITLE
[Task]: Add frontend PR a11y check

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1971] opened 2024-05-09 03:03 UTC
### Summary

Investigate pa11y-ci or axe checks

We're only using Lighthouse at the moment.

### Acceptance criteria

- a11y check on frontend PRs

**Comment by acouch** [comment] 2024-05-09 13:50
This is a dupe of #764 . Would be good to implement.

**Closed by acouch** 2024-05-09 13:50 UTC
Labels: project: grants.gov
