### ISSUE TITLE
[Task]: Make search sidebar sticky

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2146] opened 2024-09-17 20:16 UTC
---

Migrated from https://github.com/navapbc/simpler-grants-gov/issues/75
Originally created by @btabaska on *Mon, 10 Jun 2024 15:46:57 GMT*

---
### Summary

Make the search sidebar use the sticky class so that it can be scrolled independently of the results when stuck.

See https://codepen.io/andycochran/pen/BabejWq?editors=1100

This is blocked by [ issue ??? ] to implement the beta alert banner, which also uses sticky. It needs to be in place first to make sure these can both work together.

### Acceptance criteria

- Search sidebar Is sticky

**Comment by mxk0** [comment] 2024-10-10 17:03
Dupe of #1562

**Closed by mxk0** 2024-10-10 17:03 UTC
Labels: refinement, frontend, design/research
