### ISSUE TITLE
Task: Add signin endpoint

### ISSUE THREAD

**Issue by emilycnava** [HHS/simpler-grants-gov#2647] opened 2024-10-29 20:24 UTC
### Summary

Add signin endpoint to the API (for now return the URL we want the frontend to redirect to, to init the login.gov auth process)

### Acceptance criteria

Endpoint created and tested

**Comment by chouinar** [comment] 2024-11-15 18:14
Duplicate of: https://github.com/HHS/simpler-grants-gov/issues/2673

**Closed by chouinar** 2024-11-15 18:14 UTC
