### ISSUE TITLE
[ADR]: ADR for Search Engine

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1672] opened 2024-04-11 15:17 UTC
### Summary

This task is to create an ADR for the search engine. Options include OpenSearch managed by AWS, ElasticSearch hosted by Simpler or elsewhere, Postgres, and possibly others.

The favorite is OpenSearch managed by AWS currently. @chouinar and I did some research into postgres which is promising and has a lot of search features and support, so can assist in describing that option.

### Acceptance criteria

- [ ] ADR for search engine created

**Comment by mxk0** [comment] 2024-09-27 23:23
@mdragon should #684 be closed in favor of this ticket?

**Comment by mdragon** [comment] 2024-09-28 14:32
Closing as duplicate of #684

**Closed by mdragon** 2024-09-28 14:32 UTC
Labels: project: grants.gov, refinement
