### ISSUE TITLE
Update X Logo

### ISSUE THREAD

**Issue by margaretspring** [HHS/simpler-grants-gov#1716] opened 2024-04-15 17:08 UTC
Noted by Adriana at 3/28 ToT Demo.

**Comment by rylew1** [comment] 2024-04-26 20:32
@margaretspring do you know what this was about? It's on the search page?

**Comment by acouch** [comment] 2024-05-08 13:32
Closing as this is a duplicate of https://github.com/HHS/simpler-grants-gov/issues/1588

**Closed by acouch** 2024-05-08 13:32 UTC
Labels: refinement
