### ISSUE TITLE
Task: Parse login gov token

### ISSUE THREAD

**Issue by emilycnava** [HHS/simpler-grants-gov#2650] opened 2024-10-29 20:27 UTC
### Summary

Parse login gov token, extract user info, create FE token with that and pass along to FE

### Acceptance criteria

Token parsing and creation works and passes along expected data

**Comment by chouinar** [comment] 2024-11-15 18:13
Duplicate of: https://github.com/HHS/simpler-grants-gov/issues/2721

**Closed** 2024-11-15 18:13 UTC
