### ISSUE TITLE
send email to SMEs to provide more info about co design group so that they can recruit within their network

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1418] opened 2024-03-06 15:13 UTC
### Summary

-Several SMEs have indicated willingness to recruit within their network for the co design group, but are unwilling to reach out to their community until receiving more information about what the co design group will entail (including such items as time commitment, compensation, etc)
-receive and incorporate edits from MH/HHS on #1642 

### Acceptance criteria

- Edits have been incorporated
- HHS/MH have given approval
- Email has been sent

**Comment by andycochran** [comment] 2024-05-08 14:06
Duplicate of #1837

**Closed by andycochran** 2024-05-08 14:06 UTC
