### ISSUE TITLE
Move google tag manager script to head of html

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1092] opened 2024-01-25 16:05 UTC
### Summary

The google tag is currently being deployed to the body section of the html and it should be in the head. It should be in the head section of the html. There are some bugs with google tags and nextjs that are still being worked out, but we should be able to find a solution.

### Acceptance criteria

Google tag script is located in the head section of the html document.

**Comment by doug-s-nava** [comment] 2024-10-08 15:33
After looking into this here is what I've discovered:

* we are using a `GoogleAnalytics` component from the `next/third-parties/google` library available here https://github.com/vercel/next.js/blob/canary/packages/third-parties/src/google/ga.tsx
* this library is, as is mentioned in their NPM page, still experimental and under development https://www.npmjs.com/package/@next/third-parties
* this implementation seems to make use of Google Tag Manager (GTM) under the hood. See references to `googletagmanager.com` and the existence of a data layer in the source code linked above
* the GoogleAnalytics component uses the Next `Script` component to mount a script tag(s) on the page. Documentation for that component is here https://nextjs.org/docs/app/api-reference/components/script. Source code is here https://github.com/vercel/next.js/blob/canary/packages/next/src/client/script.tsx
* the Next `Script` component appears to append the script tags that it creates to the end of the document body regardless of where the component itself exists in the JSX, whenever the script strategy (see the docs for the script component above) is set to the default "afterInteractive". See https://github.com/vercel/next.js/blob/47030ae23decd06f3c1d23f71e6e69e6543ebf56/packages/next/src/client/script.tsx#L154
* the GA component uses this default strategy, but I confirmed that if we manually update the tags to use the "beforeInteractive" strategy, the tags will be inserted into the head. As far as I can tell, in this case Next is using internal caching and pre-rendering methods to load the script server side. See https://github.com/vercel/next.js/blob/47030ae23decd06f3c1d23f71e6e69e6543ebf56/packages/next/src/client/script.tsx#L323. Note that it is unclear if GA will work 100% with this implementation, but locally it seems to be working for page views at least.

Given all of that, I think our options for getting our GA tags added to the `head` of the document are:

* building our own implementation rather than relying on the library provided by Next
* forking Next's implementation and playing around with setting a server side rendering strategy for these tags
* opening an issue or PR with the Next project to allow more flexibility to the loading behavior of these tags

The final question for me is whether any of this is worth the trouble. What negative effects are we currently seeing as a result of the tags loading in the body? From what I can tell from a little research the downsides are minimal. https://www.analyticsmania.com/post/google-tag-manager-head-or-body/

**Comment by mdragon** [comment] 2024-10-29 20:04
This is fine to close for now. If we see detrimental side effects in the future we can explore the more involved solutions you laid out.

**Closed by mdragon** 2024-10-29 20:04 UTC
Labels: project: grants.gov
